version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    stdin_open: true
    tty: true

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"  # Changed host port to 11435
    volumes:
      - ollama:/root/.ollama
    stdin_open: true
    tty: true

volumes:
  ollama:
